# Generated by Django 3.2.6 on 2021-09-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название категории')),
                ('url', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=250, verbose_name='Название статьи')),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Бегущая строка', editable=False, max_length=120, verbose_name='Бегущая строка')),
                ('ticker', models.CharField(max_length=250, verbose_name='Бегущая строка')),
            ],
            options={
                'verbose_name': 'Бегущая строка',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=250, verbose_name='Название статьи')),
                ('title1', models.CharField(max_length=120, verbose_name='Короткое название 1')),
                ('title2', models.CharField(max_length=120, verbose_name='Короткое название 2')),
                ('image', models.ImageField(upload_to='article/%Y/%m/%d/', verbose_name='Картинка')),
                ('slug', models.SlugField(max_length=120, verbose_name='Slug')),
                ('short_description', models.TextField(max_length=250, verbose_name='Короткое описание')),
                ('description', models.TextField(verbose_name='Описание статьи')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('author', models.ManyToManyField(related_name='author', to='main.Author', verbose_name='Автор статьи')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.categories', verbose_name='Категории')),
            ],
        ),
    ]
