# Generated by Django 3.2.6 on 2021-09-03 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='articles',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание статьи'),
        ),
        migrations.AddField(
            model_name='articles',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Описание статьи'),
        ),
        migrations.AddField(
            model_name='articles',
            name='short_description_ru',
            field=models.TextField(max_length=250, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='articles',
            name='short_description_uz',
            field=models.TextField(max_length=250, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='articles',
            name='short_title_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='short_title_uz',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='title1_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Короткое название 1'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title1_uz',
            field=models.CharField(max_length=120, null=True, verbose_name='Короткое название 1'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title2_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Короткое название 2'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title2_uz',
            field=models.CharField(max_length=120, null=True, verbose_name='Короткое название 2'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Название статьи'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Название статьи'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='ticker_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Бегущая строка'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='ticker_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Бегущая строка'),
        ),
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='main.author', verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticker',
            name='ticker',
            field=models.CharField(max_length=500, verbose_name='Бегущая строка'),
        ),
    ]
