# Generated by Django 3.2.6 on 2021-09-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='video',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка YouTube'),
        ),
    ]
