# Generated by Django 3.2.6 on 2021-09-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210903_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='author',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='author',
            name='name_uz',
            field=models.CharField(max_length=120, null=True, verbose_name='Имя'),
        ),
    ]
