# Generated by Django 3.2.6 on 2021-09-14 07:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mainblock_bestarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='UzbNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=250, verbose_name='Название статьи')),
                ('image', models.ImageField(blank=True, upload_to='uzbnews/%Y/%m/%d/', verbose_name='Картинка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.CreateModel(
            name='WorldNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=250, verbose_name='Название новости')),
                ('image', models.ImageField(blank=True, upload_to='worldnews/%Y/%m/%d/', verbose_name='Картинка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AlterField(
            model_name='mainblock',
            name='bestArticle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bestArticle', to='main.articles', verbose_name='Лучшая статья'),
        ),
    ]
