# Generated by Django 3.2.6 on 2021-09-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210903_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AddField(
            model_name='categories',
            name='name_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_uz',
            field=models.CharField(max_length=120, null=True, verbose_name='Название категории'),
        ),
    ]
