# Generated by Django 3.2.6 on 2021-09-04 07:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210904_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание статьи'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание статьи'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='description_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание статьи'),
        ),
    ]
