# Generated by Django 3.2.6 on 2021-09-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210904_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.TextField(verbose_name='Описание статьи'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание статьи'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Описание статьи'),
        ),
    ]
