# Generated by Django 3.2.6 on 2021-09-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210914_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=250, verbose_name='Название видео 1')),
                ('link1', models.CharField(max_length=250, verbose_name='Ссылка на видео 1')),
                ('title2', models.CharField(max_length=250, verbose_name='Название видео 2')),
                ('link2', models.CharField(max_length=250, verbose_name='Ссылка на видео 2')),
                ('title3', models.CharField(max_length=250, verbose_name='Название видео 3')),
                ('link3', models.CharField(max_length=250, verbose_name='Ссылка на видео 3')),
                ('title4', models.CharField(max_length=250, verbose_name='Название видео 4')),
                ('link4', models.CharField(max_length=250, verbose_name='Ссылка на видео 4')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
