# Generated by Django 3.2.6 on 2021-09-04 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210904_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='main.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='MainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstArticle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firstArticle', to='main.articles', verbose_name='Первая статья')),
                ('secondArticle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secondArticle', to='main.articles', verbose_name='Вторая статья')),
                ('thirdArticle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thirdArticle', to='main.articles', verbose_name='Третья статья')),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
        ),
    ]
