# Generated by Django 3.2.6 on 2021-09-15 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210914_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'ВИДЕО', 'verbose_name_plural': 'ВИДЕО'},
        ),
        migrations.AddField(
            model_name='mainblock',
            name='article10',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='article10', to='main.articles', verbose_name='Статья 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainblock',
            name='article11',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='article11', to='main.articles', verbose_name='Статья 5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainblock',
            name='article12',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='article12', to='main.articles', verbose_name='Статья 6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainblock',
            name='article7',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='article7', to='main.articles', verbose_name='Статья 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainblock',
            name='article8',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='article8', to='main.articles', verbose_name='Статья 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainblock',
            name='article9',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='article9', to='main.articles', verbose_name='Статья 3'),
            preserve_default=False,
        ),
    ]
