# Generated by Django 3.2.6 on 2021-09-15 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210915_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=120, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=120, null=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(null=True, verbose_name='Описание')),
                ('picture', models.ImageField(upload_to='tests/%Y/%m/%d/', verbose_name='Картинка')),
                ('questions', models.IntegerField(default=0, verbose_name='Количество вопросов')),
                ('passage_time', models.TimeField(default=datetime.time, verbose_name='Время прохождения')),
                ('link', models.CharField(max_length=250, verbose_name='Ссылка на тест')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.TextField(default=1, max_length=250, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
