# Generated by Django 3.2.6 on 2021-09-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210915_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tests',
            options={'verbose_name': 'Тесты', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterField(
            model_name='tests',
            name='passage_time',
            field=models.SmallIntegerField(default=5, verbose_name='Время прохождения мин'),
        ),
    ]
