# Generated by Django 3.2.6 on 2021-09-22 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210916_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tests',
            name='passage_time',
            field=models.SmallIntegerField(default=0, verbose_name='Время прохождения мин'),
        ),
    ]
