# Generated by Django 3.2.6 on 2021-09-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210922_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='podcasts_audio/', verbose_name='Аудио файл')),
                ('image', models.ImageField(upload_to='podcasts/%Y/%m/%d/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Подкаст',
                'verbose_name_plural': 'Подкасты',
            },
        ),
    ]
