# Generated by Django 3.2.6 on 2021-09-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_podcasts'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcasts',
            name='author_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='podcasts',
            name='author_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='podcasts',
            name='genre_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='podcasts',
            name='genre_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='podcasts',
            name='link',
            field=models.CharField(default='hello', max_length=250, verbose_name='Сылка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcasts',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='podcasts',
            name='title_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
