# Generated by Django 3.2.6 on 2021-10-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20211031_2033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsPage',
        ),
    ]
